kind: Deployment
apiVersion: apps/v1
metadata:
  name: chai-app-deployment
  namespace: chai-app
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: chai-app
  template:
    metadata:
      labels:
        apps: chai-app
    spec:
      containers:
        - name: chai-app
          image: pkmadhubani/chai-app
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 125Mi
            limits:
              cpu: 200m
              memory: 256Mi
